%spectral estimation
%creating 64 samples
n = 0:64;
x = 3*sin(0.8*pi*n);
r = randn(size(n));
x = x + r;
[pxx, w] = periodogram(x);
figure;
plot(w,2*log10(pxx));
xlabel( 'Frequency' );
ylabel( 'dB' );
title( 'Periodogram of Sine Signal', '64 samples' );
[pxx, w] = periodogram(r);
figure;
plot(w,2*log10(pxx));
xlabel( 'Frequency' );
ylabel( 'dB' );
title( 'Periodogram of White Noise Signal','64 samples' );
[pxx, w] = pwelch(x);
figure;
plot(w,2*log10(pxx));
xlabel( 'Frequency' );
ylabel( 'dB' );
title( 'Periodogram of Sine Signal with Noise', 'with Welch Window 64 samples' );
[pxx, w] = pwelch(r);
figure;
plot(w,2*log10(pxx));
xlabel( 'Frequency' );
ylabel( 'dB' );
title( 'Periodogram of White Noise Signal', 'with Welch Window 64 samples' );
[pxx, w] = pburg(x, 4);
figure;
plot(w,2*log10(pxx));
xlabel( 'Frequency' );
ylabel( 'dB' );
title( 'Periodogram of Sine Signal with Noise', 'with ARMA Window 64 samples' );
[pxx, w] = pburg(r, 4);
figure;
plot(w,2*log10(pxx));
xlabel( 'Frequency' );
ylabel( 'dB' );
title( 'Periodogram of White Noise Signal', 'with ARMA Window 64 samples' );

%creating 128 samples
n = 0:128;
x = 3*sin(0.8*pi*n);
r = randn(size(n));
x = x + r;
[pxx, w] = periodogram(x);
figure;
plot(w,2*log10(pxx));
xlabel( 'Frequency' );
ylabel( 'dB' );
title( 'Periodogram of Sine Signal', '128 samples' );
[pxx, w] = periodogram(r);
figure;
plot(w,2*log10(pxx));
xlabel( 'Frequency' );
ylabel( 'dB' );
title( 'Periodogram of White Noise Signal', '128 samples' );
[pxx, w] = pwelch(x);
figure;
plot(w,2*log10(pxx));
xlabel( 'Frequency' );
ylabel( 'dB' );
title( 'Periodogram of Sine Signal with Noise', 'with Welch Window 128 samples' );
[pxx, w] = pwelch(r);
figure;
plot(w,2*log10(pxx));
xlabel( 'Frequency' );
ylabel( 'dB' );
title( 'Periodogram of White Noise Signal', 'with Welch Window 128 samples' );
[pxx, w] = pburg(x, 4);
figure;
plot(w,2*log10(pxx));
xlabel( 'Frequency' );
ylabel( 'dB' );
title( 'Periodogram of Sine Signal with Noise', 'with ARMA Window 128 samples' );
[pxx, w] = pburg(r, 4);
figure;
plot(w,2*log10(pxx));
xlabel( 'Frequency' );
ylabel( 'dB' );
title( 'Periodogram of White Noise Signal', 'with ARMA Window 128 samples' )
